# Generated by Django 5.0.1 on 2024-02-04 09:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="그룹 이름")),
                (
                    "team_number",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="그룹 내 팀 수",
                    ),
                ),
                ("password", models.CharField(max_length=15, verbose_name="그룹 비밀번호")),
                (
                    "type",
                    models.CharField(
                        choices=[("모각코", "모각코"), ("프로젝트", "프로젝트")],
                        max_length=20,
                        verbose_name="모임 종류",
                    ),
                ),
                (
                    "ability_description1",
                    models.CharField(max_length=100, null=True, verbose_name="실력1 설명"),
                ),
                (
                    "ability_description2",
                    models.CharField(max_length=100, null=True, verbose_name="실력2 설명"),
                ),
                (
                    "ability_description3",
                    models.CharField(max_length=100, null=True, verbose_name="실력3 설명"),
                ),
                (
                    "ability_description4",
                    models.CharField(max_length=100, null=True, verbose_name="실력4 설명"),
                ),
                (
                    "ability_description5",
                    models.CharField(max_length=100, null=True, verbose_name="실력5 설명"),
                ),
                (
                    "choice",
                    models.IntegerField(
                        default=3, null=True, verbose_name="그룹 최대 투표 개수"
                    ),
                ),
                (
                    "tech_stack",
                    models.CharField(
                        choices=[
                            ("PM", "기획"),
                            ("DESIGN", "디자인"),
                            ("FE", "프론트엔드"),
                            ("BE", "백엔드"),
                            ("SERVER", "배포/서버"),
                        ],
                        max_length=10,
                        verbose_name="기술 스택",
                    ),
                ),
                ("end_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=31, verbose_name="아이디어 이름")),
            ],
        ),
        migrations.CreateModel(
            name="AdminState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_states",
                        to="group.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_ability",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="실력",
                    ),
                ),
                (
                    "group_tech_stack",
                    models.CharField(
                        choices=[
                            ("PM", "기획"),
                            ("DESIGN", "디자인"),
                            ("FE", "프론트엔드"),
                            ("BE", "백엔드"),
                            ("SERVER", "배포/서버"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="기술 스택",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_states",
                        to="group.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
