<<<<<<< HEAD
# Generated by Django 4.1 on 2024-02-01 03:15

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='그룹 이름')),
                ('team_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='그룹 내 팀 수')),
                ('password', models.CharField(max_length=15, verbose_name='그룹 비밀번호')),
                ('ability_description1', models.CharField(max_length=100, null=True, verbose_name='실력1 설명')),
                ('ability_description2', models.CharField(max_length=100, null=True, verbose_name='실력2 설명')),
                ('ability_description3', models.CharField(max_length=100, null=True, verbose_name='실력3 설명')),
                ('ability_description4', models.CharField(max_length=100, null=True, verbose_name='실력4 설명')),
                ('ability_description5', models.CharField(max_length=100, null=True, verbose_name='실력5 설명')),
                ('choice', models.IntegerField(default=3, null=True, verbose_name='그룹 최대 투표 개수')),
                ('tech_stack', models.CharField(choices=[('PM', '기획'), ('DESIGN', '디자인'), ('FE', '프론트엔드'), ('BE', '백엔드'), ('SERVER', '배포/서버')], max_length=10, verbose_name='기술 스택')),
                ('end_date', models.DateField(default=datetime.date(2024, 2, 4))),
                ('team_building', models.ManyToManyField(related_name='participated_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
=======
# Generated by Django 4.2.6 on 2024-02-01 02:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='그룹 이름')),
                ('team_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='그룹 내 팀 수')),
                ('password', models.CharField(max_length=15, verbose_name='그룹 비밀번호')),
                ('type', models.CharField(choices=[('모각코', '모각코'), ('프로젝트', '프로젝트')], max_length=20, verbose_name='모임 종류')),
                ('ability_description1', models.CharField(max_length=100, null=True, verbose_name='실력1 설명')),
                ('ability_description2', models.CharField(max_length=100, null=True, verbose_name='실력2 설명')),
                ('ability_description3', models.CharField(max_length=100, null=True, verbose_name='실력3 설명')),
                ('ability_description4', models.CharField(max_length=100, null=True, verbose_name='실력4 설명')),
                ('ability_description5', models.CharField(max_length=100, null=True, verbose_name='실력5 설명')),
                ('choice', models.IntegerField(default=3, null=True, verbose_name='그룹 최대 투표 개수')),
                ('tech_stack', models.CharField(choices=[('PM', '기획'), ('DESIGN', '디자인'), ('FE', '프론트엔드'), ('BE', '백엔드'), ('SERVER', '배포/서버')], max_length=10, verbose_name='기술 스택')),
                ('end_date', models.DateField()),
                ('team_building', models.ManyToManyField(null=True, related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
>>>>>>> feat/#11/hajongsong
