# Generated by Django 4.1 on 2024-02-16 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team_building',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team_number',
        ),
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
        migrations.AddField(
            model_name='group',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 19)),
        ),
    ]
