# Generated by Django 4.2.6 on 2024-02-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team_number',
        ),
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='my_team_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_team_idea_set', to='group.idea'),
        ),
    ]
