# Generated by Django 5.0.1 on 2024-02-07 05:56

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="team_building",
            field=models.ManyToManyField(
                null=True, related_name="user_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="end_date",
            field=models.DateTimeField(default=datetime.date(2024, 2, 10)),
        ),
    ]
