# Generated by Django 4.2.6 on 2024-02-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
    ]
