# Generated by Django 4.2.6 on 2024-02-02 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_team_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='team_building',
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('프로젝트', '프로젝트')], max_length=20, verbose_name='모임 종류'),
        ),
    ]
