# Generated by Django 4.1 on 2024-02-01 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_type_alter_group_ability_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 4)),
        ),
    ]
