# Generated by Django 4.1 on 2024-02-02 11:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_ability_description1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='team_building',
        ),
        migrations.AlterField(
            model_name='group',
            name='ability_description1',
            field=models.CharField(max_length=100, null=True, verbose_name='실력1 설명'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ability_description2',
            field=models.CharField(max_length=100, null=True, verbose_name='실력2 설명'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ability_description3',
            field=models.CharField(max_length=100, null=True, verbose_name='실력3 설명'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ability_description4',
            field=models.CharField(max_length=100, null=True, verbose_name='실력4 설명'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ability_description5',
            field=models.CharField(max_length=100, null=True, verbose_name='실력5 설명'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AlterField(
            model_name='group',
            name='team_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='그룹 내 팀 수'),
        ),
    ]
