# Generated by Django 4.1 on 2024-02-01 06:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0003_alter_group_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31, verbose_name='아이디어 이름')),
            ],
        ),
        migrations.CreateModel(
            name='MemberState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_ability', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='실력')),
                ('group_tech_stack', models.CharField(choices=[('PM', '기획'), ('DESIGN', '디자인'), ('FE', '프론트엔드'), ('BE', '백엔드'), ('SERVER', '배포/서버')], max_length=10, verbose_name='기술 스택')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('idea_vote1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_vote1_set', to='group.idea')),
                ('idea_vote2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_vote2_set', to='group.idea')),
                ('idea_vote3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_vote3_set', to='group.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
