# Generated by Django 4.1 on 2024-02-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_end_date'),
        ('group', '0003_remove_group_choice_remove_group_team_number_and_more'),
    ]

    operations = [
    ]
