# Generated by Django 5.0.1 on 2024-02-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0003_alter_group_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
    ]
