# Generated by Django 4.1 on 2024-02-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(default='자신의 아이디어를 간단하게 소개해주세요.', max_length=1000, verbose_name='아이디어 설명'),
        ),
    ]
