# Generated by Django 4.1 on 2024-02-15 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='team_building',
        ),
        migrations.AddField(
            model_name='group',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 18)),
        ),
    ]
