# Generated by Django 4.2.6 on 2024-02-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_group_team_building_alter_group_end_date_and_more'),
        ('group', '0005_alter_memberstate_group_ability_and_more'),
    ]

    operations = [
    ]
