# Generated by Django 4.1 on 2024-02-05 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0007_alter_group_ability_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_states', to='group.group'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_states', to=settings.AUTH_USER_MODEL),
        ),
    ]
