# Generated by Django 4.2.9 on 2024-02-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_group_ability_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_states', to='group.group'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_states', to='group.group'),
        ),
    ]
