# Generated by Django 4.2.6 on 2024-02-04 16:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0008_alter_adminstate_user_alter_memberstate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='content',
            field=models.TextField(default='기본 설명', max_length=1000, verbose_name='아이디어 설명'),
        ),
        migrations.AddField(
            model_name='idea',
            name='file',
            field=models.FileField(blank=True, upload_to='idea/%Y%m%d', verbose_name='아이디어 파일'),
        ),
        migrations.AddField(
            model_name='idea',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_member_states', to='group.group'),
        ),
        migrations.AddField(
            model_name='idea',
            name='intro',
            field=models.CharField(max_length=50, null=True, verbose_name='아이디어 한 줄 소개'),
        ),
        migrations.AddField(
            model_name='idea',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='idea_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='score',
            field=models.IntegerField(default=0, verbose_name='아이디어 점수'),
        ),
        migrations.AddField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminstate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_states', to='group.group'),
        ),
        migrations.AlterField(
            model_name='adminstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 7)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=31, null=True, verbose_name='아이디어 이름'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_states', to='group.group'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
