# Generated by Django 4.2.6 on 2024-02-05 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_idea_content_idea_file_idea_group_idea_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberstate',
            name='my_team_idea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_team_idea_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 8)),
        ),
    ]
