# Generated by Django 4.2.9 on 2024-02-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_idea_content_idea_file_idea_group_idea_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(default='', verbose_name='내용'),
        ),
    ]
