# Generated by Django 4.1 on 2024-02-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_alter_memberstate_group_alter_memberstate_user'),
        ('group', '0009_idea_content_idea_file_idea_group_idea_intro_and_more'),
    ]

    operations = [
    ]
