# Generated by Django 4.2.9 on 2024-02-05 12:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0013_remove_idea_user_idea_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 8)),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='group.group')),
                ('idea_vote1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote1_set', to='group.idea')),
                ('idea_vote2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote2_set', to='group.idea')),
                ('idea_vote3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote3_set', to='group.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
