# Generated by Django 5.0.1 on 2024-02-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="idea",
            name="second_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="memberstate",
            name="my_team_idea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_team_idea_set",
                to="group.idea",
            ),
        ),
    ]
