# Generated by Django 4.1 on 2024-02-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_idea_is_selected_alter_memberstate_my_team_idea'),
        ('group', '0002_idea_is_selected_idea_second_selected_and_more'),
    ]

    operations = [
    ]
