<<<<<<<< HEAD:apps/group/migrations/0003_remove_group_choice_remove_group_team_number_and_more.py
# Generated by Django 4.1 on 2024-02-16 01:15
========
# Generated by Django 4.2.6 on 2024-02-16 13:41
>>>>>>>> 2dd49781a43f7fb9b680218e063dd96a938d532d:apps/group/migrations/0002_remove_group_choice_remove_group_team_number_and_more.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:apps/group/migrations/0003_remove_group_choice_remove_group_team_number_and_more.py
        ('group', '0002_remove_group_team_building_group_is_end'),
========
        ('group', '0001_initial'),
>>>>>>>> 2dd49781a43f7fb9b680218e063dd96a938d532d:apps/group/migrations/0002_remove_group_choice_remove_group_team_number_and_more.py
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='group',
            name='team_number',
        ),
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
        migrations.AlterField(
<<<<<<<< HEAD:apps/group/migrations/0003_remove_group_choice_remove_group_team_number_and_more.py
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 19)),
========
            model_name='memberstate',
            name='my_team_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_team_idea_set', to='group.idea'),
>>>>>>>> 2dd49781a43f7fb9b680218e063dd96a938d532d:apps/group/migrations/0002_remove_group_choice_remove_group_team_number_and_more.py
        ),
    ]
