# Generated by Django 4.2.6 on 2024-07-18 20:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0003_alter_memberstate_idea_vote1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='first_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 7, 19)),
        ),
        migrations.AlterField(
            model_name='group',
            name='second_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 7, 20)),
        ),
        migrations.AlterField(
            model_name='group',
            name='third_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 7, 21)),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote1_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote10_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote2_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote3_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote4_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote5_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote6_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote7_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote8_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote9_set', to='group.idea'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='group.idea')),
            ],
        ),
    ]
