# Generated by Django 4.2.6 on 2024-07-19 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_memberstate_idea_vote1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='first_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 7, 20)),
        ),
        migrations.AlterField(
            model_name='group',
            name='second_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 7, 21)),
        ),
        migrations.AlterField(
            model_name='group',
            name='third_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 7, 22)),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote1_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote10_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote2_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote3_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote4_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote5_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote6_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote7_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote8_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='idea_vote9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_vote9_set', to='group.idea'),
        ),
    ]
