# Generated by Django 4.1 on 2024-07-18 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_memberstate_idea_vote1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='first_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 7, 19)),
        ),
        migrations.AlterField(
            model_name='group',
            name='second_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 7, 20)),
        ),
        migrations.AlterField(
            model_name='group',
            name='third_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 7, 21)),
        ),
    ]
