# Generated by Django 4.1 on 2024-02-16 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_end_date_group_first_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='first_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 17)),
        ),
        migrations.AlterField(
            model_name='group',
            name='second_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 18)),
        ),
    ]
