# Generated by Django 4.1 on 2024-02-18 06:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='is_end',
            new_name='is_first_end',
        ),
        migrations.AddField(
            model_name='group',
            name='first_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 19)),
        ),
        migrations.AddField(
            model_name='group',
            name='is_second_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_third_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='second_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 20)),
        ),
        migrations.AddField(
            model_name='group',
            name='third_end_date',
            field=models.DateTimeField(default=datetime.date(2024, 2, 21)),
        ),
        migrations.AddField(
            model_name='memberstate',
            name='idea_vote10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_vote10_set', to='group.idea'),
        ),
        migrations.AddField(
            model_name='memberstate',
            name='idea_vote4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_vote4_set', to='group.idea'),
        ),
        migrations.AddField(
            model_name='memberstate',
            name='idea_vote5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_vote5_set', to='group.idea'),
        ),
        migrations.AddField(
            model_name='memberstate',
            name='idea_vote6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_vote6_set', to='group.idea'),
        ),
        migrations.AddField(
            model_name='memberstate',
            name='idea_vote7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_vote7_set', to='group.idea'),
        ),
        migrations.AddField(
            model_name='memberstate',
            name='idea_vote8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_vote8_set', to='group.idea'),
        ),
        migrations.AddField(
            model_name='memberstate',
            name='idea_vote9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_vote9_set', to='group.idea'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(default='기본 설명', max_length=1000, verbose_name='아이디어 설명'),
        ),
        migrations.AlterField(
            model_name='memberstate',
            name='my_team_idea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_team_idea_set', to='group.idea'),
        ),
    ]
