# Generated by Django 4.1 on 2024-02-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_rename_is_end_group_is_first_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='end_date',
        ),
    ]
